// <auto-generated>
// Generato da third-party/tabler-icons/generate.py da Tabler Icons 3.49.0 (MIT, https://tabler.io/icons):
// non modificare a mano.
// </auto-generated>

namespace VedettaVip.Web.Client.Services;

public static partial class UiIcons
{
    /// <summary>Icone dei comandi: chiave Tabler, etichetta, contenuto SVG (viewBox 0 0 24 24, tratto currentColor).</summary>
    public static readonly IReadOnlyList<MapIcon> All =
    [
        new("chart-line", "Grafici", @"<path d=""M4 19l16 0"" /> <path d=""M4 15l4 -6l4 2l4 -5l4 4"" />"),
        new("app-window", "WinBox", @"<path d=""M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10"" /> <path d=""M6 8h.01"" /> <path d=""M9 8h.01"" />"),
        new("pencil", "Modifica", @"<path d=""M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4"" /> <path d=""M13.5 6.5l4 4"" />"),
        new("trash", "Elimina", @"<path d=""M4 7l16 0"" /> <path d=""M10 11l0 6"" /> <path d=""M14 11l0 6"" /> <path d=""M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"" /> <path d=""M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"" />"),
    ];
}
