// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VedettaVip.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace VedettaVip.Api.Data.Migrations
{
    [DbContext(typeof(VedettaVipDbContext))]
    [Migration("20261007084204_AddDiscovery")]
    partial class AddDiscovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-00000000a001"),
                            ConcurrencyStamp = "admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-00000000a002"),
                            ConcurrencyStamp = "operator",
                            Name = "Operator",
                            NormalizedName = "OPERATOR"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-00000000a003"),
                            ConcurrencyStamp = "viewer",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OfflineSince")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Contacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contacts_Channel", "\"Email\" IS NOT NULL OR \"TelegramChatId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("RouterOsCredentialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SnmpCredentialId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RouterOsCredentialId");

                    b.HasIndex("SnmpCredentialId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("CpuThresholdPct")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DownAfterFailures")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("LossThresholdPct")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ParentDeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RouterOsApiEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RouterOsCredentialId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RttThresholdMs")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SnmpCredentialId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SnmpDegradedAfterFailures")
                        .HasColumnType("integer");

                    b.Property<string>("SnmpVersion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int?>("TemperatureThresholdC")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("UpAfterSuccesses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Name");

                    b.HasIndex("ParentDeviceId");

                    b.HasIndex("RouterOsCredentialId");

                    b.HasIndex("SnmpCredentialId");

                    b.ToTable("Devices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Devices_CpuThresholdPct", "\"CpuThresholdPct\" IS NULL OR \"CpuThresholdPct\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Devices_DownAfterFailures", "\"DownAfterFailures\" IS NULL OR \"DownAfterFailures\" BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Devices_ParentNotSelf", "\"ParentDeviceId\" IS NULL OR \"ParentDeviceId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_Devices_SnmpDegradedAfterFailures", "\"SnmpDegradedAfterFailures\" IS NULL OR \"SnmpDegradedAfterFailures\" BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Devices_TemperatureThresholdC", "\"TemperatureThresholdC\" IS NULL OR \"TemperatureThresholdC\" BETWEEN 0 AND 150");

                            t.HasCheckConstraint("CK_Devices_UpAfterSuccesses", "\"UpAfterSuccesses\" IS NULL OR \"UpAfterSuccesses\" BETWEEN 1 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000101"),
                            Address = "10.0.0.1",
                            Enabled = true,
                            Name = "CCR2004-CORE",
                            RouterOsApiEnabled = true,
                            SnmpVersion = "V2c",
                            Type = "Router"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000102"),
                            Address = "10.0.0.2",
                            Enabled = true,
                            Name = "CRS326-SW1",
                            ParentDeviceId = new Guid("0198f000-0000-7000-8000-000000000101"),
                            RouterOsApiEnabled = true,
                            SnmpVersion = "V2c",
                            Type = "Switch"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000103"),
                            Address = "10.0.0.3",
                            Enabled = true,
                            Name = "CRS326-SW2",
                            ParentDeviceId = new Guid("0198f000-0000-7000-8000-000000000101"),
                            RouterOsApiEnabled = true,
                            SnmpVersion = "V2c",
                            Type = "Switch"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000104"),
                            Address = "10.0.10.5",
                            Enabled = true,
                            Name = "cAP-ax-Uffici",
                            ParentDeviceId = new Guid("0198f000-0000-7000-8000-000000000102"),
                            RouterOsApiEnabled = true,
                            SnmpVersion = "V2c",
                            Type = "AccessPoint"
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceInterface", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("IfIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Alias")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OperStatus")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long?>("SpeedBps")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeviceId", "IfIndex");

                    b.ToTable("DeviceInterfaces", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceNeighbor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Board")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Capabilities")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identity")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("LocalIfIndex")
                        .HasColumnType("integer");

                    b.Property<string>("LocalInterface")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Platform")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RemoteInterface")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceNeighbors", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceStatus", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastReportAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LastRttMs")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Since")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("SnmpOk")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("DeviceId");

                    b.ToTable("DeviceStatuses", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DiscoveryIgnore", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Key");

                    b.ToTable("DiscoveryIgnores", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AlertKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromState")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("LastReminderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("NotifyAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotifyNote")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NotifyState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToState")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NotifyAfter")
                        .HasDatabaseName("IX_Events_NotifyPending")
                        .HasFilter("\"NotifyState\" = 'Pending'");

                    b.HasIndex("Time")
                        .HasDatabaseName("IX_Events_Unacknowledged")
                        .HasFilter("NOT \"Acknowledged\"");

                    b.HasIndex("DeviceId", "Time")
                        .IsDescending(false, true);

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Events_Subject", "\"DeviceId\" IS NOT NULL OR \"AgentId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MaintenanceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MapId");

                    b.ToTable("MaintenanceWindows", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceWindows_Schedule", "(\"Recurrence\" = 'Once' AND \"StartsAt\" IS NOT NULL AND \"EndsAt\" IS NOT NULL AND \"EndsAt\" > \"StartsAt\") OR\n(\"Recurrence\" = 'Weekly' AND \"StartTime\" IS NOT NULL AND \"DaysOfWeek\" BETWEEN 1 AND 127\n AND \"DurationMinutes\" BETWEEN 1 AND 10080)");

                            t.HasCheckConstraint("CK_MaintenanceWindows_Scope", "(\"Scope\" = 'All' AND \"CustomerId\" IS NULL AND \"MapId\" IS NULL AND \"DeviceId\" IS NULL) OR\n(\"Scope\" = 'Customer' AND \"CustomerId\" IS NOT NULL AND \"MapId\" IS NULL AND \"DeviceId\" IS NULL) OR\n(\"Scope\" = 'Map' AND \"MapId\" IS NOT NULL AND \"CustomerId\" IS NULL AND \"DeviceId\" IS NULL) OR\n(\"Scope\" = 'Device' AND \"DeviceId\" IS NOT NULL AND \"CustomerId\" IS NULL AND \"MapId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundImage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("GridSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ParentMapId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentMapId");

                    b.ToTable("Maps", null, t =>
                        {
                            t.HasCheckConstraint("CK_Maps_GridSize", "\"GridSize\" > 0");

                            t.HasCheckConstraint("CK_Maps_ParentNotSelf", "\"ParentMapId\" IS NULL OR \"ParentMapId\" <> \"Id\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000001"),
                            GridSize = 20,
                            Name = "Sede principale"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000002"),
                            GridSize = 20,
                            Name = "Filiale Nord",
                            ParentMapId = new Guid("0198f000-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MapLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("IfIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<long>("SpeedBps")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UtilizationThresholdPct")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("MapId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("MapLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_MapLinks_IfIndexNeedsDevice", "\"IfIndex\" IS NULL OR \"DeviceId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_MapLinks_NotLoop", "\"FromNodeId\" <> \"ToNodeId\"");

                            t.HasCheckConstraint("CK_MapLinks_SpeedBps", "\"SpeedBps\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000301"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000201"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 10000000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000302"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000201"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 10000000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000303"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000202"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 1000000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000304"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000203"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 100000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000205")
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000305"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000201"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 1000000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000206")
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LabelTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmapId")
                        .HasColumnType("uuid");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SubmapId")
                        .IsUnique()
                        .HasFilter("\"SubmapId\" IS NOT NULL");

                    b.HasIndex("MapId", "DeviceId")
                        .IsUnique()
                        .HasFilter("\"DeviceId\" IS NOT NULL");

                    b.ToTable("MapNodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_MapNodes_Kind", "(\"Kind\" = 'Device' AND \"DeviceId\" IS NOT NULL AND \"SubmapId\" IS NULL) OR\n(\"Kind\" = 'Submap' AND \"SubmapId\" IS NOT NULL AND \"DeviceId\" IS NULL) OR\n(\"Kind\" = 'Static' AND \"DeviceId\" IS NULL AND \"SubmapId\" IS NULL)");

                            t.HasCheckConstraint("CK_MapNodes_SubmapNotSelf", "\"SubmapId\" IS NULL OR \"SubmapId\" <> \"MapId\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000201"),
                            DeviceId = new Guid("0198f000-0000-7000-8000-000000000101"),
                            Kind = "Device",
                            LabelTemplate = "[Name]\n[Address]\nCPU: [Cpu]%",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 400.0,
                            Y = 100.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000202"),
                            DeviceId = new Guid("0198f000-0000-7000-8000-000000000102"),
                            Kind = "Device",
                            LabelTemplate = "[Name]\n[Address]\nCPU: [Cpu]%",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 200.0,
                            Y = 300.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000203"),
                            DeviceId = new Guid("0198f000-0000-7000-8000-000000000103"),
                            Kind = "Device",
                            LabelTemplate = "[Name]\n[Address]\nCPU: [Cpu]%",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 600.0,
                            Y = 300.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000204"),
                            DeviceId = new Guid("0198f000-0000-7000-8000-000000000104"),
                            Kind = "Device",
                            LabelTemplate = "[Name]\n[Address]\nCPU: [Cpu]%",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 200.0,
                            Y = 480.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000205"),
                            Kind = "Submap",
                            LabelTemplate = "[Name]\n(sottomappa)",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SubmapId = new Guid("0198f000-0000-7000-8000-000000000002"),
                            X = 640.0,
                            Y = 480.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000206"),
                            Kind = "Static",
                            LabelTemplate = "Internet",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 700.0,
                            Y = 100.0
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MonitoringSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("DashboardEventHours")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DefaultRouterOsCredentialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultSnmpCredentialId")
                        .HasColumnType("uuid");

                    b.Property<int>("DownAfterFailures")
                        .HasColumnType("integer");

                    b.Property<int?>("LinkUtilizationThresholdPct")
                        .HasColumnType("integer");

                    b.Property<double?>("LossThresholdPct")
                        .HasColumnType("double precision");

                    b.Property<int?>("RouterOsCpuThresholdPct")
                        .HasColumnType("integer");

                    b.Property<int?>("RouterOsTemperatureThresholdC")
                        .HasColumnType("integer");

                    b.Property<int?>("RttThresholdMs")
                        .HasColumnType("integer");

                    b.Property<int>("SnmpDegradedAfterFailures")
                        .HasColumnType("integer");

                    b.Property<int>("ThresholdWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("UpAfterSuccesses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefaultRouterOsCredentialId");

                    b.HasIndex("DefaultSnmpCredentialId");

                    b.ToTable("MonitoringSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_MonitoringSettings_DashboardHours", "\"DashboardEventHours\" BETWEEN 1 AND 168");

                            t.HasCheckConstraint("CK_MonitoringSettings_Singleton", "\"Id\" = 1");

                            t.HasCheckConstraint("CK_MonitoringSettings_Thresholds", "\"DownAfterFailures\" BETWEEN 1 AND 100 AND \"UpAfterSuccesses\" BETWEEN 1 AND 100 AND \"SnmpDegradedAfterFailures\" BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_MonitoringSettings_Window", "\"ThresholdWindowMinutes\" BETWEEN 1 AND 60");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DashboardEventHours = 4,
                            DownAfterFailures = 3,
                            LinkUtilizationThresholdPct = 80,
                            LossThresholdPct = 5.0,
                            RouterOsCpuThresholdPct = 90,
                            RouterOsTemperatureThresholdC = 75,
                            RttThresholdMs = 100,
                            SnmpDegradedAfterFailures = 2,
                            ThresholdWindowMinutes = 5,
                            UpAfterSuccesses = 2
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.NotificationDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsReminder")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("EventId");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("IX_NotificationDeliveries_Pending")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("NotificationDeliveries", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("ReminderIncludeWarnings")
                        .HasColumnType("boolean");

                    b.Property<int>("ReminderMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpFromAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SmtpFromName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SmtpPasswordProtected")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpSecurity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("SmtpValidateCertificate")
                        .HasColumnType("boolean");

                    b.Property<string>("TelegramBotTokenProtected")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("TelegramEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationSettings_Delay", "\"DelaySeconds\" BETWEEN 0 AND 3600");

                            t.HasCheckConstraint("CK_NotificationSettings_Port", "\"SmtpPort\" BETWEEN 1 AND 65535");

                            t.HasCheckConstraint("CK_NotificationSettings_Reminder", "\"ReminderMinutes\" BETWEEN 0 AND 10080");

                            t.HasCheckConstraint("CK_NotificationSettings_Singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DelaySeconds = 60,
                            EmailEnabled = false,
                            ReminderIncludeWarnings = false,
                            ReminderMinutes = 0,
                            SmtpPort = 587,
                            SmtpSecurity = "StartTls",
                            SmtpValidateCertificate = true,
                            TelegramEnabled = false,
                            TimeZoneId = "Europe/Rome"
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.OpenThresholdAlert", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid");

                    b.Property<double>("LastValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PeakValue")
                        .HasColumnType("double precision");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.HasKey("Kind", "DeviceId", "LinkId");

                    b.HasIndex("DeviceId");

                    b.ToTable("OpenThresholdAlerts", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.RouterOsCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordProtected")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<bool>("UseTls")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("VerifyCertificate")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RouterOsCredentials", null, t =>
                        {
                            t.HasCheckConstraint("CK_RouterOsCredentials_Port", "\"Port\" BETWEEN 1 AND 65535");
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.RouterOsWatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("DownReads")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("Since")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Kind", "Key")
                        .IsUnique();

                    b.ToTable("RouterOsWatches", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.SnmpCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommunityProtected")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SnmpCredentials", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NotifyRecovery")
                        .HasColumnType("boolean");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MapId");

                    b.ToTable("Subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_Scope", "(\"Scope\" = 'All' AND \"CustomerId\" IS NULL AND \"MapId\" IS NULL) OR\n(\"Scope\" = 'Customer' AND \"CustomerId\" IS NOT NULL AND \"MapId\" IS NULL) OR\n(\"Scope\" = 'Map' AND \"MapId\" IS NOT NULL AND \"CustomerId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VedettaVip.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Customer", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.RouterOsCredential", "RouterOsCredential")
                        .WithMany()
                        .HasForeignKey("RouterOsCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VedettaVip.Api.Data.Entities.SnmpCredential", "SnmpCredential")
                        .WithMany()
                        .HasForeignKey("SnmpCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RouterOsCredential");

                    b.Navigation("SnmpCredential");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "ParentDevice")
                        .WithMany()
                        .HasForeignKey("ParentDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VedettaVip.Api.Data.Entities.RouterOsCredential", "RouterOsCredential")
                        .WithMany()
                        .HasForeignKey("RouterOsCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VedettaVip.Api.Data.Entities.SnmpCredential", "SnmpCredential")
                        .WithMany()
                        .HasForeignKey("SnmpCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("ParentDevice");

                    b.Navigation("RouterOsCredential");

                    b.Navigation("SnmpCredential");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceInterface", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceNeighbor", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceStatus", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithOne("Status")
                        .HasForeignKey("VedettaVip.Api.Data.Entities.DeviceStatus", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Event", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MaintenanceWindow", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("Device");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Map", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "ParentMap")
                        .WithMany()
                        .HasForeignKey("ParentMapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMap");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MapLink", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VedettaVip.Api.Data.Entities.MapNode", "FromNode")
                        .WithMany()
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "Map")
                        .WithMany("Links")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VedettaVip.Api.Data.Entities.MapNode", "ToNode")
                        .WithMany()
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("FromNode");

                    b.Navigation("Map");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MapNode", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "Map")
                        .WithMany("Nodes")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "Submap")
                        .WithMany()
                        .HasForeignKey("SubmapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("Map");

                    b.Navigation("Submap");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MonitoringSettings", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.RouterOsCredential", null)
                        .WithMany()
                        .HasForeignKey("DefaultRouterOsCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VedettaVip.Api.Data.Entities.SnmpCredential", null)
                        .WithMany()
                        .HasForeignKey("DefaultSnmpCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VedettaVip.Api.Data.Entities.Event", "Event")
                        .WithMany("Deliveries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.OpenThresholdAlert", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.RouterOsWatch", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Subscription", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Contact", "Contact")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VedettaVip.Api.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Contact");

                    b.Navigation("Customer");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Contact", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Device", b =>
                {
                    b.Navigation("Status");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Event", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Map", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
