// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VedettaVip.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace VedettaVip.Api.Data.Migrations
{
    [DbContext(typeof(VedettaVipDbContext))]
    [Migration("20261005094319_AddMetrics")]
    partial class AddMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ParentDeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RouterOsApiEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SnmpCredentialId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnmpVersion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentDeviceId");

                    b.ToTable("Devices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Devices_ParentNotSelf", "\"ParentDeviceId\" IS NULL OR \"ParentDeviceId\" <> \"Id\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000101"),
                            Address = "10.0.0.1",
                            Enabled = true,
                            Name = "CCR2004-CORE",
                            RouterOsApiEnabled = true,
                            SnmpVersion = "V2c",
                            Type = "Router"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000102"),
                            Address = "10.0.0.2",
                            Enabled = true,
                            Name = "CRS326-SW1",
                            ParentDeviceId = new Guid("0198f000-0000-7000-8000-000000000101"),
                            RouterOsApiEnabled = true,
                            SnmpVersion = "V2c",
                            Type = "Switch"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000103"),
                            Address = "10.0.0.3",
                            Enabled = true,
                            Name = "CRS326-SW2",
                            ParentDeviceId = new Guid("0198f000-0000-7000-8000-000000000101"),
                            RouterOsApiEnabled = true,
                            SnmpVersion = "V2c",
                            Type = "Switch"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000104"),
                            Address = "10.0.10.5",
                            Enabled = true,
                            Name = "cAP-ax-Uffici",
                            ParentDeviceId = new Guid("0198f000-0000-7000-8000-000000000102"),
                            RouterOsApiEnabled = true,
                            SnmpVersion = "V2c",
                            Type = "AccessPoint"
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceInterface", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("IfIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Alias")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OperStatus")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long?>("SpeedBps")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeviceId", "IfIndex");

                    b.ToTable("DeviceInterfaces", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceStatus", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastReportAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LastRttMs")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Since")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("SnmpOk")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("DeviceId");

                    b.ToTable("DeviceStatuses", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Time")
                        .HasDatabaseName("IX_Events_Unacknowledged")
                        .HasFilter("NOT \"Acknowledged\"");

                    b.HasIndex("DeviceId", "Time")
                        .IsDescending(false, true);

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundImage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("GridSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ParentMapId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentMapId");

                    b.ToTable("Maps", null, t =>
                        {
                            t.HasCheckConstraint("CK_Maps_GridSize", "\"GridSize\" > 0");

                            t.HasCheckConstraint("CK_Maps_ParentNotSelf", "\"ParentMapId\" IS NULL OR \"ParentMapId\" <> \"Id\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000001"),
                            GridSize = 20,
                            Name = "Sede principale"
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000002"),
                            GridSize = 20,
                            Name = "Filiale Nord",
                            ParentMapId = new Guid("0198f000-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MapLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("IfIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<long>("SpeedBps")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("MapId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("MapLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_MapLinks_IfIndexNeedsDevice", "\"IfIndex\" IS NULL OR \"DeviceId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_MapLinks_NotLoop", "\"FromNodeId\" <> \"ToNodeId\"");

                            t.HasCheckConstraint("CK_MapLinks_SpeedBps", "\"SpeedBps\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000301"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000201"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 10000000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000302"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000201"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 10000000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000303"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000202"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 1000000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000304"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000203"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 100000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000205")
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000305"),
                            FromNodeId = new Guid("0198f000-0000-7000-8000-000000000201"),
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SpeedBps = 1000000000L,
                            ToNodeId = new Guid("0198f000-0000-7000-8000-000000000206")
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LabelTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmapId")
                        .HasColumnType("uuid");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SubmapId")
                        .IsUnique()
                        .HasFilter("\"SubmapId\" IS NOT NULL");

                    b.HasIndex("MapId", "DeviceId")
                        .IsUnique()
                        .HasFilter("\"DeviceId\" IS NOT NULL");

                    b.ToTable("MapNodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_MapNodes_Kind", "(\"Kind\" = 'Device' AND \"DeviceId\" IS NOT NULL AND \"SubmapId\" IS NULL) OR\n(\"Kind\" = 'Submap' AND \"SubmapId\" IS NOT NULL AND \"DeviceId\" IS NULL) OR\n(\"Kind\" = 'Static' AND \"DeviceId\" IS NULL AND \"SubmapId\" IS NULL)");

                            t.HasCheckConstraint("CK_MapNodes_SubmapNotSelf", "\"SubmapId\" IS NULL OR \"SubmapId\" <> \"MapId\"");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000201"),
                            DeviceId = new Guid("0198f000-0000-7000-8000-000000000101"),
                            Kind = "Device",
                            LabelTemplate = "[Name]\n[Address]\nCPU: [Cpu]%",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 400.0,
                            Y = 100.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000202"),
                            DeviceId = new Guid("0198f000-0000-7000-8000-000000000102"),
                            Kind = "Device",
                            LabelTemplate = "[Name]\n[Address]\nCPU: [Cpu]%",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 200.0,
                            Y = 300.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000203"),
                            DeviceId = new Guid("0198f000-0000-7000-8000-000000000103"),
                            Kind = "Device",
                            LabelTemplate = "[Name]\n[Address]\nCPU: [Cpu]%",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 600.0,
                            Y = 300.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000204"),
                            DeviceId = new Guid("0198f000-0000-7000-8000-000000000104"),
                            Kind = "Device",
                            LabelTemplate = "[Name]\n[Address]\nCPU: [Cpu]%",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 200.0,
                            Y = 480.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000205"),
                            Kind = "Submap",
                            LabelTemplate = "[Name]\n(sottomappa)",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            SubmapId = new Guid("0198f000-0000-7000-8000-000000000002"),
                            X = 640.0,
                            Y = 480.0
                        },
                        new
                        {
                            Id = new Guid("0198f000-0000-7000-8000-000000000206"),
                            Kind = "Static",
                            LabelTemplate = "Internet",
                            MapId = new Guid("0198f000-0000-7000-8000-000000000001"),
                            X = 700.0,
                            Y = 100.0
                        });
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "ParentDevice")
                        .WithMany()
                        .HasForeignKey("ParentDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentDevice");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceInterface", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.DeviceStatus", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithOne("Status")
                        .HasForeignKey("VedettaVip.Api.Data.Entities.DeviceStatus", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Event", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Map", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "ParentMap")
                        .WithMany()
                        .HasForeignKey("ParentMapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMap");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MapLink", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VedettaVip.Api.Data.Entities.MapNode", "FromNode")
                        .WithMany()
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "Map")
                        .WithMany("Links")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VedettaVip.Api.Data.Entities.MapNode", "ToNode")
                        .WithMany()
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("FromNode");

                    b.Navigation("Map");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.MapNode", b =>
                {
                    b.HasOne("VedettaVip.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "Map")
                        .WithMany("Nodes")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VedettaVip.Api.Data.Entities.Map", "Submap")
                        .WithMany()
                        .HasForeignKey("SubmapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("Map");

                    b.Navigation("Submap");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Device", b =>
                {
                    b.Navigation("Status");
                });

            modelBuilder.Entity("VedettaVip.Api.Data.Entities.Map", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
